import { Inter } from "next/font/google";
import { Allura } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const allura = Allura({
  weight: "400",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin", "latin-ext"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        className={`${inter.variable} bg-custom-background bg-cover bg-center`}
      >
        {/* Dark overlay */}
        <div className="absolute inset-0 bg-black opacity-70 z-[-1]"></div>

        {/* Add blur to background image */}
        <div className="absolute inset-0 blur-sm z-[-2]"></div>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
